

LANGUAGE_CHOICES = [
        ('uz', 'Uzbek'),
        ('ru', 'Russian'),
        ('en', 'English'),
    ]


DESCRIPTIONS = {
    "peace": "🧑🏻 Tinch aholi! Vazifangiz — mafiyani topish va kunduzgi ovoz berishda ularni osish.",
    "don": "🤵🏻 Don — Mafialar sardori. Har tunda kim o'lishini siz hal qilasiz.",
    "mafia": "🤵🏼 Mafia. Don buyruqlariga bo'ysunasiz. Don o'lsa uning o'rnini egallashingiz mumkin.",
    "killer": "🔪 Qotil. Siz yakka o'ynaysiz. Maqsadingiz — hammadan tirik qolish.",
    "com": "🕵🏻‍♂ Komissar katani. Siz tinch aholining asosiy himoyachisisiz va mafiyani fosh qilasiz.",
    "doc": "🧑🏻‍⚕ Doktor. Har tunda bir o'yinchini o'limdan saqlab qolishingiz mumkin.",
    "serg": "👮🏻 Serjant. Komissarning yordamchisi. Komissar o'lsa uning o'rnini egallaysiz.",
    "daydi": "🧙🏻‍♂ Daydi. Tunda tanlagan uyga borib u yerda bo'lgan hodisalarga guvoh bo'lishingiz mumkin.",
    "lover": "💃🏻 Ma'shuqa. Tunda bir o'yinchini uyquga ketkazib, 1 kun harakat qila olmaydigan qilasiz.",
    "snowball": "☃️ Qorbolla. Har tunda bir o'yinchini qor bilan o'ldira olasiz. Yakka rollar tarafidasiz.",
    "ninja": "🥷 Ninja. Tunda yashirincha bir o'yinchini nayza bilan o'ldirasiz. Yakka rol.",
    "nogiron": "👨🏻‍🦼 Nogiron. Siz faqat tinch aholi tarafdasiz va ovoz berishda qatnashasiz.",
    "ghost": "👻 Arvoh. Sizni faqat Ninja o'ldira oladi. Ovoz berishda qatnashasiz, tinch aholi tarafidasiz.",
    "clon": " 🧬 Klon Siz har tunda 1 ta o'yinchini tanlaysiz. Agar o'sha o'yinchi o'lsa, siz uning rolini egallaysiz. Yakka rol ",
    "drunk": "🍻 Alkash. Bir o'yinchini o'ldirishingiz mumkin, lekin o'zingiz ham o'lishingiz ehtimoli bor. Yakka rol.",
    "vampire_old": "🧛🏻‍♂ Qa'ri vampir. Sizni faqat osish yoki Vampir ovchisi o'ldira oladi. Ba'zan bir kechada 2 kishini o'ldirishingiz mumkin.",
    "vampirehunter": "🗡 Vampir ovchisi. Siz faqat Qa'ri vampirni o'ldira olasiz. Tinch aholi tarafidasiz.",
    "rage": "🧟 G'azabkor. Har tunda o'yinchi tanlaysiz. Maxsus sharoitda tanlaganlar bilan birga o'lishingiz mumkin.",
    "fraud": "🤹🏻 Aferist. Kunduzgi ovoz berishda bir o'yinchining ovozini o'g'irlab olishingiz mumkin.",
    "mermaid": "🧜🏻‍♀ Suvparisi. Har tunda bir o'yinchini cho'ktirib o'ldirasiz. Komissar sizni o'ldira olmaydi.",
    "traveler": "🏃🏻 Sayohatchi. Tunda boshqa o'yinchining rolini vaqtincha olib o'ynaysiz.",
    "elf": "🧝🏻‍♂ Elf. Tinch aholini himoya qilasiz va yovuz rollarga qarshi kurashasiz.",
    "kam": "💣 Kamikaze. Agar sizni osishsa, xohlagan o'yinchini o'zingiz bilan olib ketishingiz mumkin.",
    "adv": "👨🏻‍💼 Advokat. Mafialar tarafdori. Tanlagan mafiani Komissar tinch aholi deb ko'radi.",
    "journalist": "👩🏻‍💻 Jurnalist. Mafialar agenti. Tunda o'yinchilarni tekshirib, ma'lumotni mafiyaga yetkazasiz.",
    "cooker": "🧑🏻‍🍳 Sehrli oshpaz. Mafiya yoki yakka rollarga zaharli ovqat berasiz, tinch aholi zarar ko'rmaydi.",
    "nurse": "👩🏻‍⚕ Hamshira. Doktorning yordamchisi. Doktor o'lsa uning o'rnini egallaysiz.",
    "rich": "💸 Boy. Har tunda bir o'yinchiga pul sovg'a qilasiz.",
    "suid": "🤦🏻 Suidsid. Agar sizni osishsa, siz g'alaba qozonasiz.",
    "hero":"🥷 Geroy - bu o'yinda kun vaqtida ham o'yinchilarni o'ldirishga imkon beradigan, boshqa geroylar xujumidan ximoya qiladigan yordamchi personaj.",
    "spy": "🦇 Ayg'oqchi. Mafialar tarafdori. Tunda o'yinchining rolini bilib mafiyaga oshkor qilasiz.",
}

ROLES_CHOICES = [
    ("peace", "🧑🏻 Tinch aholi"),
    ("don", "🤵🏻 Don"),
    ("mafia", "🤵🏼 Mafia"),
    ("killer", "🔪 Qotil"),
    ("com", "🕵🏻‍♂ Komissar katani"),
    ("doc", "🧑🏻‍⚕ Doktor"),
    ("serg", "👮🏻 Serjant"),
    ("daydi", "🧙🏻‍♂ Daydi"),
    ("lover", "💃🏻 Ma'shuqa"),
    ("snowball", "☃️ Qorbolla"),
    ("ninja", "🥷 Ninja"),
    ("nogiron", "👨🏻‍🦼 Nogiron"),
    ("ghost", "👻 Arvoh"),
    ("clone", "☘ Narkobaron"),
    ("drunk", "🍻 Alkash"),
    ("vampireold", "🧛🏻‍♂ Qa'ri vampir"),
    ("vampirehunter", "🗡 Vampir ovchisi"),
    ("rage", "🧟 G'azabkor"),
    ("fraud", "🤹🏻 Aferist"),
    ("mermaid", "🧜🏻‍♀ Suvparisi"),
    ("traveler", "🏃🏻 Sayohatchi"),
    ("elf", "🧝🏻‍♂ Elf"),
    ("kam", "💣 Kamikaze"),
    ("adv", "👨🏻‍💼 Advokat"),
    ("journalist", "👩🏻‍💻 Jurnalist"),
    ("cooker", "🧑🏻‍🍳 Sehrli oshpaz"),
    ("nurse", "👩🏻‍⚕ Hamshira"),
    ("rich", "💸 Boy"),
    ("suid", "🤦🏻 Suidsid"),
    ("spy", "🦇 Ayg'oqchi"),
    ("hero", "🥷 Geroy"),
    ("back_main", "⬅️ Orqaga"),
    
]
ROLES_BY_COUNT = {
    4:  ["peace","nogiron","don","doc"],
    5:  ["peace","nogiron","don","doc","com"],
    6:  ["peace","nogiron","don","mafia","doc","com"],
    7:  ["peace","nogiron","don","mafia","doc","com","daydi"],
    8:  ["peace","nogiron","don","mafia","doc","com","daydi","lover"],
    9:  ["peace","nogiron","don","mafia","doc","com","daydi","lover","kam"],
    10: ["peace","nogiron","don","mafia","doc","com","daydi","lover","kam","cooker"],
    11: ["peace","nogiron","don","mafia","doc","com","daydi","lover","kam","cooker","nurse"],
    12: ["peace","nogiron","don","mafia","doc","com","daydi","lover","kam","cooker","nurse","peace"],
    13: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy"],
    14: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer"],
    15: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv"],
    16: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja"],
    17: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud"],
    18: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist"],
    19: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist","rich"],
    20: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist","rich","traveler"],
    21: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist","rich","traveler","clone"],
    22: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist","rich","traveler","clone","drunk"],
    23: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","adv","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost"],
    24: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","adv","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf"],
    25: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv"],
    26: ["peace","nogiron","don","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv","suid"],
    27: ["peace","nogiron","don","mafia","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv","suid"],
    28: ["peace","nogiron","don","mafia","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv","suid","vampirehunter"],
    29: ["peace","nogiron","don","mafia","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv","suid","vampirehunter","rage"],
    30: ["peace","nogiron","don","mafia","mafia","mafia","doc","com","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","adv","suid","vampirehunter","rage","vampireold"],
    31: ["peace","nogiron","adv","don","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    32: ["peace","nogiron","adv","don","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    33: ["peace","nogiron","adv","peace","don","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    34: ["peace","nogiron","adv","peace","don","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    35: ["peace","nogiron","adv","peace","don","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    36: ["peace","peace","adv","peace","nogiron","don","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    37: ["peace","peace","adv","peace","nogiron","don","mafia","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    38: ["peace","peace","adv","peace","nogiron","don","mafia","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    39: ["peace","peace","adv","peace","nogiron","peace","don","mafia","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
    40: ["peace","peace","adv","peace","nogiron","peace","don","mafia","mafia","mafia","mafia","mafia","doc","com","serg","daydi","lover","kam","cooker","nurse","spy","killer","killer","snowball","ninja","fraud","journalist","rich","traveler","clone","drunk","ghost","elf","mermaid","suid","vampirehunter","rage","vampireold"],
}




ACTIONS = {

    # 🔴 MAFIA SIDE
    "don_kill": "🤵🏻 Don, bugun kimni o'ldiramiz?",
    "mafia_vote": "🤵🏼 Mafialar, qurbonni tanlang:",
    "adv_mask": "👨🏻‍💼 Qaysi mafiani yashiramiz?",
    "spy_check": "🦇 Kimning rolini aniqlaymiz?",
    "journalist_check": "👩🏻‍💻 Kimdan ma'lumot olamiz?",

    # 🟢 PEACE SIDE
    "doc_heal": "🧑🏻‍⚕️ Kimni davolaymiz?",
    "com_check": "🕵🏻‍♂ Kimni tekshiramiz?",
    "com_shoot": "🔫 Kimni otamiz?",
    "serg_check": "👮🏻 Komissar o'rniga kimni tekshiramiz?",
    "daydi_watch": "🧙🏻‍♂ Kimning uyiga boramiz?",
    "lover_block": "💃🏻 Kimni bugun blok qilamiz?",
    "cooker_poison": "🧑🏻‍🍳 Kimga zaharli ovqat beramiz?",
    "rich_give": "💸 Kimga pul beramiz?",
    "elf_attack": "🧝🏻‍♂ Yovuz rolga hujum qilamiz, kimni tanlaysiz?",
    "vampirehunter_kill": "🗡 Qaysi o'yinchi Qa'ri vampir deb o'ylaysiz?",

    # 🟡 SOLO / CHAOS
    "killer_kill": "🔪 Kimni yo'q qilamiz?",
    "snowball_kill": "☃️ Kimni muzlatamiz?",
    "ninja_kill": "🥷 Kimga yashirin hujum qilamiz?",
    "clone": "🧬 Kimni tanlamoqchisiz?",
    "drunk_action": "🍻 Kimga hujum qilamiz? (o'zingiz ham o'lishingiz mumkin)",
    "fraud_steal_vote": "🤹🏻 Kimning ovozini o'g'irlaymiz?",
    "mermaid_kill": "🧜🏻‍♀ Kimni cho'ktirib yuboramiz?",
    "traveler_copy": "🏃🏻 Kimning rolini vaqtincha olamiz?",
    "ghost_vote": "👻 Arvoh ovoz bermoqda...",
    "nogiron_vote": "👨🏻‍🦼 Ovoz berish vaqti",
    "kam_choose": "💣 Osilish oldidan kimni o'zingiz bilan olib ketasiz?",
    "suid_win": "🤦🏻 Sizni osishdi — siz yutdingiz!",
    "rage_mark": "🧟 Kimni belgilaymiz?",
    "vampire_old_kill": "🧛🏻‍♂ Qa'ri vampir, qurbon(lar)ni tanlang:",

}


MONEY_FOR_STAR ={
    "1000": 7,
    "10000": 77,
    "50000": 340,
    "100000": 680,
}

STONE_FOR_STAR = {
    "1": 7,
    "10": 68,
    "30": 185,
    "50": 237,
    "70": 382,
    "100": 513,
}

ROLE_PRICES_IN_STONES = {
    "don": 4,
    "com": 4,
    "ninja": 4,
    "vampire_old": 5,

    "killer": 3,
    "snowball": 3,
    "mermaid": 3,
    "clone": 3,
    "vampirehunter": 3,
    "rage": 3,

    "adv": 2,
    "spy": 2,
    "journalist": 2,
    "cooker": 2,
    "lover": 2,
    "traveler": 2,
    "elf": 2,

    "doc": 2,
    "serg": 1,
    "nurse": 1,
    "daydi": 1,
    "rich": 1,
    "fraud": 1,
    "ghost": 1,
    "nogiron": 1,
    "drunk": 1,
    "kam": 1,
    "suid": 1,
    "peace": 0,
    "mafia": 1,
}

ROLE_PRICES_IN_MONEY = {
    "don": 1200,
    "com": 1200,
    "ninja": 1100,
    "vampire_old": 1500,

    "killer": 900,
    "snowball": 850,
    "mermaid": 850,
    "clone": 850,
    "vampirehunter": 800,
    "rage": 800,

    "adv": 600,
    "spy": 600,
    "journalist": 550,
    "cooker": 550,
    "lover": 500,
    "traveler": 500,
    "elf": 500,

    "doc": 500,
    "serg": 300,
    "nurse": 300,
    "daydi": 300,
    "rich": 250,
    "fraud": 250,
    "ghost": 250,
    "nogiron": 200,
    "drunk": 200,
    "kam": 200,
    "suid": 150,
    "peace": 100,
    "mafia": 200,
}


ROLE_EMOJI = {
    "peace": "🧑🏻",
    "doc": "🧑🏻‍⚕️",
    "nurse": "👩🏻‍⚕️",
    "daydi": "🧙🏻‍♂️",
    "com": "🕵🏻‍♂️",
    "serg": "👮🏻",
    "lover": "💃🏻",
    "cooker": "🧑🏻‍🍳",
    "rich": "💸",
    "elf": "🧝🏻‍♂️",
    "vampirehunter": "🗡",
    "nogiron": "👨🏻‍🦼",
    "ghost": "👻",

    "don": "🤵🏻",
    "mafia": "🤵🏼",
    "adv": "👨🏻‍💼",
    "spy": "🦇",
    "journalist": "👩🏻‍💻",

    "killer": "🔪",
    "ninja": "🥷",
    "snowball": "☃️",
    "clone": "☘️",
    "drunk": "🍻",
    "mermaid": "🧜🏻‍♀️",
    "traveler": "🏃🏻",
    "fraud": "🤹🏻",
    "kam": "💣",
    "suid": "🤦🏻",
    "rage": "🧟",
    "vampire_old": "🧛🏻‍♂️",
}
